--启动mysql
mysqld --console

#控制台登陆数据库
mysql -u root -p;

#修改密码
alter user 'root'@'localhost' identified by '123456';

#安装模块
pip install pymysql

CREATE DATABASE ORDER1;

USE ORDER1;

CREATE TABLE IF NOT EXISTS `PERSONS`(
   `ID_P` INT,
   `LASTNAME` VARCHAR(100),
   `FIRSTNAME` VARCHAR(100),
   `ADDRESS` VARCHAR(100),
   `CITY` VARCHAR(100),
   `CREATEDATE` DATE
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

INSERT INTO PERSONS (ID_P, LASTNAME, FIRSTNAME, ADDRESS, CITY, CREATEDATE) VALUES ('0', 'HUANG', 'QINGLIN', 'TIANHE', 'GUANGZHOU', NOW());

SHOW TABLES;

CREATE TABLE IF NOT EXISTS `PERSONS_HIS`(
   `ID_P` INT,
   `LASTNAME` VARCHAR(100),
   `FIRSTNAME` VARCHAR(100),
   `ADDRESS` VARCHAR(100),
   `CITY` VARCHAR(100),
   `CREATEDATE` DATE
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

SELECT * FROM PERSONS ORDER BY CREATEDATE DESC LIMIT 1;

